ALTER TABLE entries ADD COLUMN IF NOT EXISTS sighting_queen BOOLEAN;
ALTER TABLE entries ADD COLUMN IF NOT EXISTS sighting_larvae BOOLEAN;
ALTER TABLE entries ADD COLUMN IF NOT EXISTS sighting_eggs BOOLEAN;
ALTER TABLE entries ADD COLUMN IF NOT EXISTS sighting_brood BOOLEAN;
ALTER TABLE entries ADD COLUMN IF NOT EXISTS occupied_combs INTEGER;
ALTER TABLE entries ADD COLUMN IF NOT EXISTS queen_cells INTEGER;
ALTER TABLE entries ADD COLUMN IF NOT EXISTS varroa_mites BOOLEAN;
