ALTER TABLE hive_colors ADD COLUMN IF NOT EXISTS sighting_queen BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE hive_colors ADD COLUMN IF NOT EXISTS sighting_larvae BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE hive_colors ADD COLUMN IF NOT EXISTS sighting_eggs BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE hive_colors ADD COLUMN IF NOT EXISTS sighting_brood BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE hive_colors ADD COLUMN IF NOT EXISTS occupied_combs INTEGER;
ALTER TABLE hive_colors ADD COLUMN IF NOT EXISTS queen_cells INTEGER;
ALTER TABLE hive_colors ADD COLUMN IF NOT EXISTS varroa_mites BOOLEAN;
